server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-register
          uri: lb://ms-register
          predicates:
            - Path=/api/v1/user/**
        - id: ms-documents
          uri: lb://ms-documents
          predicates:
            - Path=/api/v1/document/**   # Corregido aquí
        - id: ms-evaluation
          uri: lb://ms-evaluation
          predicates:
            - Path=/api/v1/evaluation/**  # Corregido aquí
        - id: ms-credit
          uri: lb://ms-credit
          predicates:
            - Path=/api/v1/credit/**  # Corregido aquí
        - id: ms-simulation
          uri: lb://ms-simulation
          predicates:
            - Path=/api/v1/simulation/**  # Corregido aquí
