apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-credit-deployment
  labels:
    app: ms-credit-deployment
spec:
  selector:
    matchLabels:
      app: ms-credit-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-credit-deployment
    spec:
      containers:
        - name: ms-credit
          image: cesarrodriguezpardo/ms-credit
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_ORDERS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT_ORDERS
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_NAME_ORDERS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: DB_PASSWORD
