server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/CesarRodriguezPardo/microservicios_kubernetes
          search-paths: config-data
  application:
    name: config-service
